opam-version: "2.0"
synopsis: "Small OCaml compatibility build inspired by TigerBeetle"
description: "An OCaml rewrite of a small TigerBeetle-compatible surface for experimentation and learning."
maintainer: "tusharhqq"
authors: ["tusharhqq"]
dev-repo: "git+https://github.com/tusharhqq/6666.git"
depends: [
  "ocaml" {>= "5.4"}
  "dune" {>= "3.21"}
  "yojson"
  "base-unix"
  "base-threads"
  "alcotest" {with-test}
  "qcheck" {with-test}
]
build: [
  ["dune" "build"]
]
