(lang dune 3.11)
(name tigerbeetle_ocaml)
(generate_opam_files true)

(package
 (name tigerbeetle_ocaml)
 (synopsis "OCaml ledger state machine for the pinned TigerBeetle source tree")
 (depends
  (ocaml (>= 5.2))
  oxcaml
  base
  (qcheck :with-test)))
